FROM node:alpine

WORKDIR /app/backend

COPY ./utils/package.json ./
COPY ./utils/yarn.lock ./

RUN yarn install

COPY ./utils ./utils

WORKDIR /app/backend/question-service

COPY ./question-service/package.json ./
COPY ./question-service/yarn.lock ./

RUN yarn install

COPY ./question-service ./

EXPOSE 8003

CMD ["yarn", "dev"]