FROM node:alpine

WORKDIR /app/backend/history-service

COPY ./history-service/package.json ./
COPY ./history-service/yarn.lock ./

RUN yarn install

COPY ./history-service ./

EXPOSE 8005

CMD ["yarn", "dev"]