
FROM node:alpine

WORKDIR /app/backend/collaboration-service

COPY ./collaboration-service/package.json ./
COPY ./collaboration-service/yarn.lock ./

RUN yarn install

COPY ./collaboration-service ./

EXPOSE 8004

CMD ["yarn", "dev"]