FROM amd64/node:alpine AS build-stage

WORKDIR /history-service

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM amd64/node:alpine AS prod-stage

WORKDIR /history-service

COPY ./package.json ./

RUN yarn install --production

COPY --from=build-stage /history-service/dist .

ENV DB_CLOUD_URI=mongodb+srv://cs3219:cs3219@cluster0.bnrscil.mongodb.net/?retryWrites=true&w=majority
ENV ENV=production
ENV PORT=8005

EXPOSE 8005

CMD ["node", "app.js"]
