import { SKILL, TOPIC } from './enums';

export const NAVBAR_HEIGHT_PX = 64;
export const RESIZER_HEIGHT_WIDTH_PX = 14;
export const JWT_TOKEN_KEY = 'jwt-token';
export const LOGIN_TIMEOUT_STATUS_CODE = 440;

export const TopicSkillMapping: Record<SKILL, TOPIC[]> = {
  ADVANCED: [
    TOPIC.BACKTRACKING,
    TOPIC.DIVIDECONQUER,
    TOPIC.DP,
    TOPIC.MEMOIZATION,
    TOPIC.MONOTONICSTACK,
    TOPIC.QUICKSELECT,
    TOPIC.SEGMENTTREE,
    TOPIC.TOPOSORT,
    TOPIC.TRIE,
    TOPIC.UNIONFIND,
  ],
  INTERMEDIATE: [
    TOPIC.BFS,
    TOPIC.BINARYSEARCH,
    TOPIC.DFS,
    TOPIC.GREEDY,
    TOPIC.HASHTABLE,
    TOPIC.MATH,
    TOPIC.RECURSION,
    TOPIC.TREE,
  ],
  FUNDAMENTAL: [
    TOPIC.ARRAY,
    TOPIC.LINKEDLIST,
    TOPIC.MATRIX,
    TOPIC.STACK,
    TOPIC.STRING,
    TOPIC.SORTING,
    TOPIC.TWOPOINTERS,
    TOPIC.QUEUE,
  ],
};
