export enum SERVICE {
  USER = 'USER',
  MATCHING = 'MATCHING',
  QUESTION = 'QUESTION',
  COLLABORATION = 'COLLABORATION',
  HISTORY = 'HISTORY',
  COMMUNICATION = 'COMMUNICATION',
}

export enum HTTP_METHOD {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}

export enum DIFFICULTY {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum LANGUAGE {
  PYTHON = 'PYTHON',
  JAVA = 'JAVA',
  CPP = 'C++',
  JAVASCRIPT = 'JAVASCRIPT',
}

export enum VIEW {
  QUESTION = 'QUESTION',
  EDITOR = 'EDITOR',
  CHAT = 'CHAT',
}

export enum SKILL {
  ADVANCED = 'ADVANCED',
  INTERMEDIATE = 'INTERMEDIATE',
  FUNDAMENTAL = 'FUNDAMENTAL',
}

export enum TOPIC {
  ARRAY = 'ARRAY',
  BACKTRACKING = 'BACKTRACKING',
  BFS = 'BREADTH-FIRST SEARCH',
  BINARYSEARCH = 'BINARY SEARCH',
  DFS = 'DEPTH-FIRST SEARCH',
  DIVIDECONQUER = 'DIVIDE AND CONQUER',
  DP = 'DYNAMIC PROGRAMMING',
  LINKEDLIST = 'LINKED LIST',
  GREEDY = 'GREEDY',
  HASHTABLE = 'HASH TABLE',
  MATH = 'MATH',
  MATRIX = 'MATRIX',
  MEMOIZATION = 'MEMOIZATION',
  MONOTONICSTACK = 'MONOTONIC STACK',
  RECURSION = 'RECURSION',
  SEGMENTTREE = 'SEGMENT TREE',
  STACK = 'STACK',
  STRING = 'STRING',
  SORTING = 'SORTING',
  TOPOSORT = 'TOPOLOGICAL SORT',
  TREE = 'TREE',
  TRIE = 'TRIE',
  TWOPOINTERS = 'TWO POINTERS',
  QUEUE = 'QUEUE',
  QUICKSELECT = 'QUICKSELECT',
  UNIONFIND = 'UNION FIND',
}

export enum ADVANCED {
  BACKTRACKING = 'BACKTRACKING',
  DIVIDECONQUER = 'DIVIDE AND CONQUER',
  DP = 'DYNAMIC PROGRAMMING',
  MEMOIZATION = 'MEMOIZATION',
  MONOTONICSTACK = 'MONOTONIC STACK',
  QUICKSELECT = 'QUICKSELECT',
  SEGMENTTREE = 'SEGMENT TREE',
  TOPOSORT = 'TOPOLOGICAL SORT',
  TRIE = 'TRIE',
  UNIONFIND = 'UNION FIND',
}

export enum INTERMEDIATE {
  BFS = 'BREADTH-FIRST SEARCH',
  BINARYSEARCH = 'BINARY SEARCH',
  DFS = 'DEPTH-FIRST SEARCH',
  GREEDY = 'GREEDY',
  HASHTABLE = 'HASH TABLE',
  MATH = 'MATH',
  RECURSION = 'RECURSION',
  TREE = 'TREE',
}

export enum FUNDAMENTAL {
  ARRAY = 'ARRAY',
  LINKEDLIST = 'LINKED LIST',
  MATRIX = 'MATRIX',
  STACK = 'STACK',
  STRING = 'STRING',
  SORTING = 'SORTING',
  TWOPOINTERS = 'TWO POINTERS',
  QUEUE = 'QUEUE',
}
