export enum SERVICE {
  USER = 'USER',
  MATCHING = 'MATCHING',
  QUESTION = 'QUESTION',
  COLLABORATION = 'COLLABORATION',
  HISTORY = 'HISTORY',
  COMMUNICATION = 'COMMUNICATION',
}

export enum HTTP_METHOD {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}

export enum DIFFICULTY {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum LANGUAGE {
  PYTHON = 'PYTHON',
}

export enum VIEW {
  QUESTION = 'QUESTION',
  EDITOR = 'EDITOR',
  CHAT = 'CHAT',
}
