FROM amd64/node:alpine AS build-stage

WORKDIR /question-service

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM amd64/node:alpine AS prod-stage

ARG DB_URI

WORKDIR /question-service

COPY ./package.json ./

RUN yarn install --production

COPY --from=build-stage /question-service/dist .

ENV DB_URI=${DB_URI}
ENV ENV=production
ENV PORT=8003

EXPOSE 8003

CMD ["node", "app.js"]
