export enum DIFFICULTY {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum LANGUAGE {
  PYTHON = 'PYTHON',
  JAVA = 'JAVA',
  CPP = 'C++',
  JAVASCRIPT = 'JAVASCRIPT',
}

export enum TOPIC {
  ARRAY = 'ARRAY',
  BACKTRACKING = 'BACKTRACKING',
  BFS = 'BREADTH-FIRST SEARCH',
  BINARYSEARCH = 'BINARY SEARCH',
  DFS = 'DEPTH-FIRST SEARCH',
  DIVIDECONQUER = 'DIVIDE AND CONQUER',
  DP = 'DYNAMIC PROGRAMMING',
  LINKEDLIST = 'LINKED LIST',
  GREEDY = 'GREEDY',
  HASHTABLE = 'HASH TABLE',
  MATH = 'MATH',
  MATRIX = 'MATRIX',
  MEMOIZATION = 'MEMOIZATION',
  MONOTONICSTACK = 'MONOTONIC STACK',
  RECURSION = 'RECURSION',
  SEGMENTTREE = 'SEGMENT TREE',
  STACK = 'STACK',
  STRING = 'STRING',
  SORTING = 'SORTING',
  TOPOSORT = 'TOPOLOGICAL SORT',
  TREE = 'TREE',
  TRIE = 'TRIE',
  TWOPOINTERS = 'TWO POINTERS',
  QUEUE = 'QUEUE',
  QUICKSELECT = 'QUICKSELECT',
  UNIONFIND = 'UNION FIND',
}
